name: Pull Request Code Verification | a pull request's creation triggers a GitHub Actions workflow

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main


jobs:
  lint:
    name: Lint Code with Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Wheel
        run: |
          pip install wheel

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run Flake8 linter
        run: |
          flake8 . 

  tests:
    name: Run Unit Tests with Pytest
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Wheel
        run: |
          pip install wheel

      - name: Install dependencies from requirements.txt
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/


  