name: Pull Request Code Verification | a pull request's creation triggers a GitHub Actions workflow

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main


jobs:
  code-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"

    


