name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v2 
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Trigger Azure ML job
      run: az ml job create --file src/job_compute_cluster.yml --resource-group resGrp --workspace-name ws01

    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"


