name: Train Model on Push to Main

on:
  push:
    branches:
      - main

jobs:
  experiment:
    name: Train Model in Development Environment
    runs-on: ubuntu-latest
    environment: 
      name: Development

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Azure CLI and ML extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v2 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run experiment job
        run: az ml job create --file src/job_compute_cluster.yml --resource-group resGrp --workspace-name ws01
  
  production:
    name: Train Model in Production Environment
    runs-on: ubuntu-latest
    needs: experiment
    environment:
      name: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Azure AZ ML extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v2 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run production job
        run: az ml job create --file src/job_compute_cluster_prod.yml --resource-group resGrp --workspace-name ws01 --stream
