name: Deploy Model to Online Endpoint

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy Model
    runs-on: ubuntu-latest
  
    environment:
      name: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Azure AZ ML extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v2 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register the Model
        run: |
          MODEL_NAME="diabetes-model"
          RUN_ID="helpful_airport_pkrmq6dzhj"
          OUTPUT="mlflow_log_model_455706061"
          MODEL_PATH="azureml:azureml_$RUN_ID_output_$OUTPUT:1"
          az ml model create --name $MODEL_NAME --path $MODEL_PATH

      - name: Deploy Model to Endpoint
        run: |
          # Register the latest model from the MLflow run
          MODEL_NAME="diabetes-model"
          ENDPOINT_NAME="diabetes-endpoint-$(date +%s)"

          # Create an online endpoint
          az ml online-endpoint create --name $ENDPOINT_NAME -f create-endpoint.yaml

          # Deploy the model to the endpoint
          az ml online-deployment create --name blue --endpoint $ENDPOINT_NAME --model $MODEL_NAME:1 --all-traffic

      - name: Get Endpoint Details
        run: |
          ENDPOINT_NAME="diabetes-endpoint-$(date +%s)"
          SCORING_URI=$(az ml online-endpoint show --name $ENDPOINT_NAME --query scoring_uri -o tsv)
          echo "Scoring URI: $SCORING_URI"


        
