name: Deploy Model to Online Endpoint

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy Model
    runs-on: ubuntu-latest
  
    environment:
      name: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Azure AZ ML extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v2 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register Model
        run: |
          MODEL_NAME="diabetes-model"
          RUN_ID="helpful_airport_pkrmq6dzhj"
          MODEL_PATH="model"
          az ml model create --name $MODEL_NAME --type "mlflow_model" --path azureml://jobs/$RUN_ID/outputs/artifacts/$MODEL_PATH --resource-group resGrp --workspace-name ws01

      - name: Check if Endpoint Exists
        id: check_endpoint
        run: |
          export ENDPOINT_NAME="diabetes-endpoint"
          az ml online-endpoint show --name $ENDPOINT_NAME --resource-group resGrp --workspace-name ws01 > /dev/null 2>&1 || echo "Endpoint does not exist" 

      - name: Create Endpoint
        if: steps.check_endpoint.outputs.Endpoint == ''
        run: |
          export ENDPOINT_NAME="diabetes-endpoint"
          az ml online-endpoint create --name $ENDPOINT_NAME -f create-endpoint.yml --resource-group resGrp --workspace-name ws01

      - name: Update Endpoint
        if: steps.check_endpoint.outputs.Endpoint != ''
        run: |
          export ENDPOINT_NAME="diabetes-endpoint"
          az ml online-endpoint update --name $ENDPOINT_NAME --resource-group resGrp --workspace-name ws01

      - name: Deploy Model to Endpoint
        run: |
          az ml online-deployment create --file mlflow-deployment.yml --resource-group resGrp --workspace-name ws01 --all-traffic

      - name: Get Endpoint Details
        run: |
          export ENDPOINT_NAME="diabetes-endpoint"
          SCORING_URI=$(az ml online-endpoint show --name $ENDPOINT_NAME --query scoring_uri -o tsv)
          echo "Scoring URI: $SCORING_URI"